name: "Build and Publish"

# Trigger when commits are pushed to the master branch
on:
  push:
    branches:
      - main

jobs:
  build-push:
    name: "Build and Publish Custom Caddy Version"
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
            echo "Installing Caddy"
            wget https://golang.org/dl/go1.16.3.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.16.3.linux-amd64.tar.gz
            curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/gpg.key' | sudo apt-key add -
            curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-xcaddy.list
            echo "Installing XCaddy"
            sudo apt update && sudo apt install xcaddy
            echo 'PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc && exec bash && echo $PATH
            echo "Buildung custom Caddy"
            xcaddy build --with github.com/caddy-dns/cloudflare
      - name: version
        run: echo "::set-output name=version::$(./caddy -v)"
        id: version
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}