name: "Build and Publish"

# Trigger when commits are pushed to the master branch
on:
  push:
    branches:
      - main

jobs:
  build-push:
    name: "Build and Publish Custom Caddy Version"
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: make install
      - name: version
        run: echo "::set-output name=version::$(./caddy -v)"
        id: version
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}